'use server'

import { createClient } from '@/lib/supabase/server'
import type { StatusPemesanan } from '@/lib/types/database'

export async function createPemesanan(formData: FormData) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) {
    return { error: 'Anda harus login terlebih dahulu' }
  }

  const ruanganId = formData.get('ruangan_id') as string
  const tanggalMulai = formData.get('tanggal_mulai') as string
  const tanggalSelesai = formData.get('tanggal_selesai') as string
  const jamMulai = formData.get('jam_mulai') as string | null
  const jamSelesai = formData.get('jam_selesai') as string | null
  const totalHarga = Number(formData.get('total_harga'))
  const catatanPenyewa = formData.get('catatan_penyewa') as string || ''

  // Get the ruangan to find the owner
  const { data: ruangan, error: ruanganError } = await supabase
    .from('ruangan')
    .select('pemilik_id')
    .eq('id', ruanganId)
    .single()

  if (ruanganError || !ruangan) {
    return { error: 'Ruangan tidak ditemukan' }
  }

  // Check for overlapping bookings (double-booking prevention)
  const { data: existingBookings } = await supabase
    .from('pemesanan')
    .select('id, tanggal_mulai, tanggal_selesai, jam_mulai, jam_selesai')
    .eq('ruangan_id', ruanganId)
    .in('status', ['PENDING', 'MENUNGGU_VERIFIKASI', 'DIKONFIRMASI'])
    .lte('tanggal_mulai', tanggalSelesai)
    .gte('tanggal_selesai', tanggalMulai)

  if (existingBookings && existingBookings.length > 0) {
    // If times are provided, we check for more granular overlap
    if (jamMulai && jamSelesai) {
      const isOverlap = existingBookings.some(b => {
        // If the existing booking also has times and is on the same day
        if (b.jam_mulai && b.jam_selesai && b.tanggal_mulai === tanggalMulai) {
          return (jamMulai < b.jam_selesai && jamSelesai > b.jam_mulai);
        }
        // If the existing booking is a full-day booking covering this day
        return true; 
      });

      if (isOverlap) {
        return { error: 'Maaf, ruangan sudah dipesan pada waktu tersebut. Silakan pilih jam atau tanggal lain.' }
      }
    } else {
      // If booking is a full-day booking, any collision is an error
      return { error: 'Maaf, ruangan sudah dipesan pada tanggal tersebut. Silakan pilih tanggal lain.' }
    }
  }

  // NEW: Check for blocked dates (Maintenance/Event)
  const { data: blockedDates } = await supabase
    .from('blokir_tanggal')
    .select('id, alasan')
    .eq('ruangan_id', ruanganId)
    .lte('tanggal_mulai', tanggalSelesai)
    .gte('tanggal_selesai', tanggalMulai)

  if (blockedDates && blockedDates.length > 0) {
    return { error: `Maaf, ruangan sedang tidak tersedia karena: ${blockedDates[0].alasan || 'Maintenance'}.` }
  }

  const { data, error } = await supabase
    .from('pemesanan')
    .insert({
      ruangan_id: ruanganId,
      penyewa_id: user.id,
      pemilik_id: ruangan.pemilik_id,
      tanggal_mulai: tanggalMulai,
      tanggal_selesai: tanggalSelesai,
      jam_mulai: jamMulai || null,
      jam_selesai: jamSelesai || null,
      total_harga: totalHarga,
      status: 'PENDING' as StatusPemesanan,
      catatan_penyewa: catatanPenyewa,
      bukti_pembayaran_url: '',
      catatan_pemilik: '',
      kode_pemesanan: '', // Will be auto-generated by the trigger
    })
    .select()
    .single()

  if (error) {
    console.error('Error creating pemesanan:', error)
    return { error: error.message }
  }

  return { data, error: null }
}

export async function uploadBuktiPembayaran(pemesananId: string, formData: FormData) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) {
    return { error: 'Anda harus login terlebih dahulu' }
  }

  const file = formData.get('bukti') as File
  if (!file) {
    return { error: 'File bukti pembayaran diperlukan' }
  }

  // Upload file to Supabase Storage
  const fileExt = file.name.split('.').pop()
  const fileName = `${user.id}/${pemesananId}-${Date.now()}.${fileExt}`

  const { error: uploadError } = await supabase.storage
    .from('bukti-pembayaran')
    .upload(fileName, file)

  if (uploadError) {
    console.error('Upload error:', uploadError)
    return { error: 'Gagal mengunggah file. Coba lagi.' }
  }

  // Get the public URL
  const { data: urlData } = supabase.storage
    .from('bukti-pembayaran')
    .getPublicUrl(fileName)

  // Update pemesanan with the proof URL and change status
  const { error: updateError } = await supabase
    .from('pemesanan')
    .update({
      bukti_pembayaran_url: urlData.publicUrl,
      status: 'MENUNGGU_VERIFIKASI' as StatusPemesanan,
    })
    .eq('id', pemesananId)
    .eq('penyewa_id', user.id) // Ensure the user is the renter

  if (updateError) {
    return { error: updateError.message }
  }

  return { success: true }
}

export async function getTenantPemesanan() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) return [] as TenantBooking[]

  const { data, error } = await supabase
    .from('pemesanan')
    .select(`
      *,
      ruangan(id, nama, lokasi, kota, foto_utama, harga_per_hari)
    `)
    .eq('penyewa_id', user.id)
    .order('dibuat_pada', { ascending: false })

  if (error) {
    console.error('Error fetching tenant pemesanan:', error)
    return [] as TenantBooking[]
  }

  return (data || []) as unknown as TenantBooking[]
}

// Explicit types for joined queries that Supabase generics can't infer
export interface TenantBooking {
  id: string
  kode_pemesanan: string
  ruangan_id: string
  penyewa_id: string
  pemilik_id: string
  tanggal_mulai: string
  tanggal_selesai: string
  total_harga: number
  status: string
  bukti_pembayaran_url: string
  catatan_penyewa: string
  dibuat_pada: string
  diperbarui_pada: string
  ruangan?: {
    id: string
    nama: string
    lokasi: string
    kota: string
    foto_utama: string
    harga_per_hari: number
  }
}

export async function getOwnerPemesanan(status?: StatusPemesanan) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) return []

  let query = supabase
    .from('pemesanan')
    .select(`
      *,
      ruangan(id, nama, lokasi, foto_utama),
      profil:penyewa_id(id, nama_lengkap, email, avatar_url)
    `)
    .eq('pemilik_id', user.id)
    .order('dibuat_pada', { ascending: false })

  if (status) {
    query = query.eq('status', status)
  }

  const { data, error } = await query

  if (error) {
    console.error('Error fetching owner pemesanan:', error)
    return []
  }

  return (data || []).map((p) => ({
    ...p,
    penyewa: p.profil,
    profil: undefined,
  }))
}

export async function verifyPemesanan(pemesananId: string, action: 'approve' | 'reject', catatan?: string) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) {
    return { error: 'Tidak terautentikasi' }
  }

  const newStatus: StatusPemesanan = action === 'approve' ? 'DIKONFIRMASI' : 'DITOLAK'

  const updateData: Record<string, unknown> = {
    status: newStatus,
    diverifikasi_pada: new Date().toISOString(),
  }

  if (catatan) {
    updateData.catatan_pemilik = catatan
  }

  const { error } = await supabase
    .from('pemesanan')
    .update(updateData)
    .eq('id', pemesananId)
    .eq('pemilik_id', user.id) // Ensure the user is the owner

  if (error) {
    return { error: error.message }
  }

  return { success: true }
}

export async function cancelPemesanan(pemesananId: string) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) {
    return { error: 'Tidak terautentikasi' }
  }

  const { error } = await supabase
    .from('pemesanan')
    .update({
      status: 'DIBATALKAN' as StatusPemesanan,
      dibatalkan_pada: new Date().toISOString(),
    })
    .eq('id', pemesananId)
    .eq('penyewa_id', user.id) // Only tenant can cancel
    .in('status', ['PENDING', 'DITOLAK']) // Can only cancel PENDING or DITOLAK

  if (error) {
    return { error: error.message }
  }

  return { success: true }
}

export async function getOwnerStats() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) return null

  // Get total revenue (DIKONFIRMASI + SELESAI bookings)
  const { data: confirmedBookings } = await supabase
    .from('pemesanan')
    .select('total_harga')
    .eq('pemilik_id', user.id)
    .in('status', ['DIKONFIRMASI', 'SELESAI'])

  const totalRevenue = (confirmedBookings || []).reduce((sum, b) => sum + b.total_harga, 0)

  // Get pending verification count
  const { count: pendingCount } = await supabase
    .from('pemesanan')
    .select('*', { count: 'exact', head: true })
    .eq('pemilik_id', user.id)
    .eq('status', 'MENUNGGU_VERIFIKASI')

  // Get total spaces
  const { count: totalSpaces } = await supabase
    .from('ruangan')
    .select('*', { count: 'exact', head: true })
    .eq('pemilik_id', user.id)

  // Get total bookings count (all statuses)
  const { count: totalBookings } = await supabase
    .from('pemesanan')
    .select('*', { count: 'exact', head: true })
    .eq('pemilik_id', user.id)

  // Get confirmed bookings count for occupancy calculation
  const { count: confirmedCount } = await supabase
    .from('pemesanan')
    .select('*', { count: 'exact', head: true })
    .eq('pemilik_id', user.id)
    .in('status', ['DIKONFIRMASI', 'SELESAI'])

  const occupancyRate = totalBookings && totalBookings > 0
    ? Math.round(((confirmedCount || 0) / totalBookings) * 100)
    : 0

  return {
    totalRevenue,
    pendingCount: pendingCount || 0,
    totalSpaces: totalSpaces || 0,
    totalBookings: totalBookings || 0,
    confirmedCount: confirmedCount || 0,
    occupancyRate,
  }
}

/**
 * HELPER: Memastikan URL gambar valid dan menunjuk ke bucket foto-ruangan
 * Versi ULTRA-RESILIENT: Menggunakan hardcoded Project ID jika ENV gagal
 */
function sanitizeImageUrl(url: string | null): string {
  const fallback = "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80";
  if (!url || url === '' || url === 'undefined' || url === 'null') return fallback;
  
  const PROJECT_ID = "abvpmrfdbuccbheuovvv";
  const HARDCODED_BASE = `https://${PROJECT_ID}.supabase.co`;
  let supabaseUrl = (process.env.NEXT_PUBLIC_SUPABASE_URL || HARDCODED_BASE).trim();
  
  supabaseUrl = supabaseUrl.replace(/['"]/g, '');
  if (supabaseUrl.endsWith('/')) supabaseUrl = supabaseUrl.slice(0, -1);
  
  if (url.includes('supabase.co/storage/v1/object/public/')) {
    const parts = url.split('/public/');
    const bucketAndPath = parts[parts.length - 1];
    return `${supabaseUrl}/storage/v1/object/public/${bucketAndPath}`;
  } 
  
  if (url.startsWith('http')) return url;

  let path = url.replace(/\/+/g, '/');
  if (path.startsWith('/')) path = path.substring(1);
  return `${supabaseUrl}/storage/v1/object/public/foto-ruangan/${path}`;
}

export async function getOwnerRuangan() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) return []

  const { data, error } = await supabase
    .from('ruangan')
    .select(`
      *,
      ruangan_fasilitas(
        fasilitas(*)
      ),
      foto_ruangan(*)
    `)
    .eq('pemilik_id', user.id)
    .order('dibuat_pada', { ascending: false })

  if (error) {
    console.error('Error fetching owner ruangan:', error)
    return []
  }

  return (data || []).map((ruangan) => {
    const r = {
      ...ruangan,
      fasilitas: (ruangan.ruangan_fasilitas || []).map((rf: { fasilitas: unknown }) => rf.fasilitas).filter(Boolean),
      ruangan_fasilitas: undefined,
    }
    // Sanitize images
    r.foto_utama = sanitizeImageUrl(r.foto_utama);
    if (r.foto_ruangan) {
      r.foto_ruangan = r.foto_ruangan.map((f: any) => ({
        ...f,
        url: sanitizeImageUrl(f.url)
      }))
    }
    return r
  })
}

export async function getOwnerConfirmedTransactions() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) return []

  const { data, error } = await supabase
    .from('pemesanan')
    .select(`
      *,
      ruangan(id, nama),
      profil:penyewa_id(id, nama_lengkap, avatar_url)
    `)
    .eq('pemilik_id', user.id)
    .in('status', ['DIKONFIRMASI', 'SELESAI'])
    .order('diverifikasi_pada', { ascending: false })

  if (error) {
    console.error('Error fetching transactions:', error)
    return []
  }

  return (data || []).map((p) => ({
    ...p,
    penyewa: p.profil,
    profil: undefined,
  }))
}

export async function getOwnerCalendarData() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) return { spaces: [], bookings: [] }

  // Get all spaces owned by the user
  const { data: spaces, error: spacesError } = await supabase
    .from('ruangan')
    .select('id, nama, tipe')
    .eq('pemilik_id', user.id)

  if (spacesError) {
    console.error('Error fetching calendar spaces:', spacesError)
    return { spaces: [], bookings: [] }
  }

  // Get all bookings for these spaces
  const { data: bookings, error: bookingsError } = await supabase
    .from('pemesanan')
    .select(`
      id,
      ruangan_id,
      tanggal_mulai,
      tanggal_selesai,
      jam_mulai,
      jam_selesai,
      status,
      total_harga,
      ruangan(nama)
    `)
    .eq('pemilik_id', user.id)
    .in('status', ['DIKONFIRMASI', 'SELESAI', 'MENUNGGU_VERIFIKASI', 'PENDING'])

  if (bookingsError) {
    console.error('Error fetching calendar bookings:', bookingsError)
    return { spaces: spaces || [], bookings: [] }
  }

  return {
    spaces: spaces || [],
    bookings: bookings || [],
  }
}

export async function blockTanggal(ruanganId: string, tanggalMulai: string, tanggalSelesai: string, alasan: string) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) return { error: 'Tidak terautentikasi' }

  const { error } = await supabase
    .from('blokir_tanggal')
    .insert({
      ruangan_id: ruanganId,
      pemilik_id: user.id,
      tanggal_mulai: tanggalMulai,
      tanggal_selesai: tanggalSelesai,
      alasan: alasan,
    })

  if (error) return { error: error.message }
  return { success: true }
}

export async function deleteBlockTanggal(id: string) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) return { error: 'Tidak terautentikasi' }

  const { error } = await supabase
    .from('blokir_tanggal')
    .delete()
    .eq('id', id)
    .eq('pemilik_id', user.id)

  if (error) return { error: error.message }
  return { success: true }
}

// Update getOwnerCalendarData to also fetch blocked dates
export async function getOwnerCalendarDataExtended() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) return { spaces: [], bookings: [], blockedDates: [] }

  const { data: spaces } = await supabase
    .from('ruangan')
    .select('id, nama, tipe')
    .eq('pemilik_id', user.id)

  const { data: bookings } = await supabase
    .from('pemesanan')
    .select('*, ruangan(id, nama), penyewa:profil!penyewa_id(id, nama_lengkap, email, nomor_telepon, avatar_url)')
    .eq('pemilik_id', user.id)
    .in('status', ['DIKONFIRMASI', 'SELESAI', 'MENUNGGU_VERIFIKASI', 'PENDING'])

  const { data: blockedDates } = await supabase
    .from('blokir_tanggal')
    .select('*, ruangan(nama)')
    .eq('pemilik_id', user.id)

  return {
    spaces: spaces || [],
    bookings: bookings || [],
    blockedDates: blockedDates || [],
  }
}

export async function getBlockedDates(ruanganId: string) {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from('blokir_tanggal')
    .select('tanggal_mulai, tanggal_selesai, alasan')
    .eq('ruangan_id', ruanganId)
    .gte('tanggal_selesai', new Date().toISOString().split('T')[0]) // Only future or current blocks

  if (error) {
    console.error('Error fetching blocked dates:', error)
    return []
  }

  return data || []
}
